/* NULL · catalog.ts
   The library. Entries are plain objects: adding a game is adding a line.

   Two shelves feed it. The hand-written ones below are files this repo
   serves itself. On top of them sits `discovered.ts`, generated by
   scripts/discover-games.mjs from the gmshelf shelves (seraph, truffled, the
   Chicken King's Vault and the Ultimate Game Stash) — thousands of games
   nobody had to type in. Nothing is fetched at runtime: the shelf is a file in
   the repo, rebuilt whenever the script runs.

   A discovered row is a path, not an address, which is what keeps two and a
   half thousand of them to a couple of hundred kilobytes. The shelves are all
   mirrored by raw.githack, and that expansion happens here, once.

   `file` is either a real path inside the built site or an https URL; the
   player frames the first kind directly and bridges the second (see
   Player.tsx). `thumb` is optional artwork, same deal. */

import { ROWS } from "./discovered";

export type Kind = "game" | "app" | "proxy";

export type Entry = {
  id: string;
  name: string;
  kind: Kind;
  /** where it opens. A game or app: a file or URL. A proxy: a site. */
  file?: string;
  url?: string;
  /** optional artwork. Without one the card shows a plain square and a glyph */
  thumb?: string;
  labels: string[];
  status?: "Fine" | "Rough" | "Blocked" | "Remote";
  warning?: { title: string; body: string };
};

const GAMES: Entry[] = [];

const APPS: Entry[] = [];

const PROXIES: Entry[] = [
  {
    id: "internet-archive",
    name: "Internet Archive",
    kind: "proxy",
    url: "https://archive.org/",
    labels: ["Archive", "Books", "Software"],
    status: "Fine",
  },
  {
    id: "wikipedia",
    name: "Wikipedia",
    kind: "proxy",
    url: "https://www.wikipedia.org/",
    labels: ["Reference", "Reading"],
    status: "Fine",
  },
  {
    id: "openstreetmap",
    name: "Openstreetmap",
    kind: "proxy",
    url: "https://www.openstreetmap.org/",
    labels: ["Maps", "Reference"],
    status: "Rough",
  },
];

/** Where the shelves are mirrored. raw.githack and nothing else: it is the
 *  one host that hands html back as html and javascript back as javascript,
 *  and a browser will not run a page — or the scripts inside it — that it has
 *  been told is text. */
const MIRROR = "https://raw.githack.com";

/** What a shelf is called on a card. */
const SHELF_NAME: Record<string, string> = {
  "gmshelf/seraph": "Seraph",
  "gmshelf/truffled": "Truffled",
  "gmshelf/ckv": "CKV",
  "gmshelf/ugs": "UGS",
};

/** The address of a file inside a shelf. */
const inShelf = (shelf: string, file: string) => `${MIRROR}/${shelf}/main/${file}`;

/** Discovered games, marked as remote so a card can say where it loads from.
 *  Local entries win a name clash: this repo's own shelf is always the one
 *  it serves. */
function discovered(): Entry[] {
  const local = new Set(GAMES.map((g) => g.name.toLowerCase()));
  return ROWS.filter(([, name]) => !local.has(name.toLowerCase())).map(
    ([id, name, shelf, file, coverShelf, cover, genre]) => ({
      id,
      name,
      kind: "game" as const,
      file: inShelf(shelf, file),
      ...(cover ? { thumb: inShelf(coverShelf, cover) } : {}),
      labels: [SHELF_NAME[shelf] ?? shelf, ...(genre ? [genre] : []), "Remote"],
      status: "Remote" as const,
    }),
  );
}

export const LIBRARY: Record<Kind, Entry[]> = {
  game: [...GAMES, ...discovered()],
  app: APPS,
  proxy: PROXIES,
};

export function entries(kind: Kind): Entry[] {
  return LIBRARY[kind];
}

export function find(kind: Kind, id: string): Entry | undefined {
  return LIBRARY[kind].find((e) => e.id === id);
}

/** Where each entry came from, for the source dropdown: a discovered game
 *  carries the stash it was pulled from as its first label, and anything this
 *  repo serves itself answers to NULL. "Remote" is not a source, it is a note
 *  about how the card loads, so it is left out. */
const NOT_A_SOURCE = new Set(["Remote"]);

export function sources(kind: Kind): { id: string; count: number }[] {
  const tally = new Map<string, number>();
  LIBRARY[kind].forEach((e) => {
    const from = e.labels.find((l) => !NOT_A_SOURCE.has(l)) ?? "NULL";
    tally.set(from, (tally.get(from) ?? 0) + 1);
  });
  return [...tally.entries()]
    .map(([id, count]) => ({ id, count }))
    .sort((a, b) => b.count - a.count || a.id.localeCompare(b.id));
}

/** Every category in one kind, alphabetical, for the filters row. */
export function categories(kind: Kind): string[] {
  const seen = new Set<string>();
  LIBRARY[kind].forEach((e) => e.labels.forEach((l) => seen.add(l)));
  return [...seen].sort((a, b) => a.localeCompare(b));
}

export function counts() {
  return {
    game: LIBRARY.game.length,
    app: LIBRARY.app.length,
    proxy: LIBRARY.proxy.length,
  };
}

export type SortId = "az" | "za" | "new" | "random";

export const SORTS: { id: SortId; name: string }[] = [
  { id: "az", name: "A to Z" },
  { id: "za", name: "Z to A" },
  { id: "new", name: "Recently added" },
  { id: "random", name: "Shuffled" },
];

/** Filter + sort in one pass. The search matches the name and every label,
 *  which is why categories are searchable without being printed on a card. */
export function browse(
  kind: Kind,
  opts: { q?: string; sort?: SortId; onlyIds?: string[]; seed?: number; source?: string },
): Entry[] {
  const q = (opts.q ?? "").trim().toLowerCase();
  const sort = opts.sort ?? "az";
  let list = LIBRARY[kind].slice();

  if (opts.onlyIds) {
    const set = new Set(opts.onlyIds);
    list = list.filter((e) => set.has(e.id));
  }
  if (opts.source) {
    list = list.filter((e) => (e.labels.find((l) => !NOT_A_SOURCE.has(l)) ?? "NULL") === opts.source);
  }
  if (q) {
    list = list.filter(
      (e) =>
        e.name.toLowerCase().includes(q) ||
        e.id.includes(q) ||
        e.labels.some((l) => l.toLowerCase().includes(q)),
    );
  }

  if (sort === "az") list.sort((a, b) => a.name.localeCompare(b.name));
  else if (sort === "za") list.sort((a, b) => b.name.localeCompare(a.name));
  else if (sort === "random") list = shuffled(list, opts.seed ?? 7);

  return list;
}

function shuffled<T>(list: T[], seed: number): T[] {
  const out = list.slice();
  let s = seed || 1;
  for (let i = out.length - 1; i > 0; i--) {
    s = (s * 1103515245 + 12345) & 0x7fffffff;
    const j = s % (i + 1);
    [out[i], out[j]] = [out[j], out[i]];
  }
  return out;
}
