/* NULL · catalog.ts
   The library. Entries are plain objects: adding a game is adding a line.

   Two shelves feed it. The hand-written ones below are files this repo
   serves itself. On top of them sits `discovered.ts`, generated by
   scripts/discover-games.mjs from the gmshelf shelves (seraph, truffled, the
   Chicken King's Vault and the Ultimate Game Stash) — thousands of games
   nobody had to type in. Nothing is fetched at runtime: the shelf is a file in
   the repo, rebuilt whenever the script runs.

   A discovered row is a path, not an address, which is what keeps two and a
   half thousand of them to a couple of hundred kilobytes. The shelves are all
   mirrored by raw.githack, and that expansion happens here, once.

   `file` is either a real path inside the built site or an https URL; the
   player frames the first kind directly and bridges the second (see
   Player.tsx). `thumb` is optional artwork, same deal. */

import { CLOUD, ROWS } from "./discovered";

export type Kind = "game" | "app" | "proxy";

/** Where the cloud shelf belongs. Those titles are not files anywhere: they are
 *  streamed by a service that holds the licence and brokers each session, so
 *  the card can name them and say where they live, and that is honest — a
 *  made-up embed URL would only be a broken tile with extra steps. */
export const CLOUD_SITE = "https://cherrion.top/";

export type Entry = {
  id: string;
  name: string;
  kind: Kind;
  /** where it opens. A game or app: a file or URL. A proxy: a site. */
  file?: string;
  url?: string;
  /** optional artwork. Without one the card shows a drawn square instead */
  thumb?: string;
  /** the same artwork at other addresses, best first. `thumb` is the first of
   *  them: a filtered network refuses whole hosts, and one refused host should
   *  not cost a card its picture (see Cover.tsx) */
  thumbs?: string[];
  labels: string[];
  status?: "Fine" | "Rough" | "Blocked" | "Remote";
  warning?: { title: string; body: string };
};

const GAMES: Entry[] = [];

/* ---------- apps ----------
   The tools shelf. Every one of these is somebody else's site, opened the way
   the games are — through the player, which tries a copy, then an inline
   mount, then a plain frame — so the shelf is a list of things worth having,
   not a list of things NULL hosts. Nothing here needs a key, an account or an
   install, which is the only rule an entry has to follow.

   `status` is about the frame and nothing else: "Fine" is a page that
   happily lives inside one (most of the static ones, and anything on GitHub
   Pages), "Rough" is a site that may refuse to be framed and is best opened
   in the proxy window instead. The player's route button walks a Rough one on
   to the next road, which is usually enough. */
const APPS: Entry[] = [
  { id: "cyberchef", name: "CyberChef", kind: "app", file: "https://gchq.github.io/CyberChef/", labels: ["Tools", "Data"], status: "Fine" },
  { id: "excalidraw", name: "Excalidraw", kind: "app", file: "https://excalidraw.com/", labels: ["Drawing", "Boards"], status: "Fine" },
  { id: "tldraw", name: "tldraw", kind: "app", file: "https://www.tldraw.com/", labels: ["Drawing", "Boards"], status: "Fine" },
  { id: "witeboard", name: "Witeboard", kind: "app", file: "https://witeboard.com/", labels: ["Drawing", "Boards"], status: "Rough" },
  { id: "photopea", name: "Photopea", kind: "app", file: "https://www.photopea.com/", labels: ["Images", "Editing"], status: "Fine" },
  { id: "squoosh", name: "Squoosh", kind: "app", file: "https://squoosh.app/", labels: ["Images", "Editing"], status: "Fine" },
  { id: "svgviewer", name: "SVG Viewer", kind: "app", file: "https://www.svgviewer.dev/", labels: ["Images", "Code"], status: "Fine" },
  { id: "desmos", name: "Desmos", kind: "app", file: "https://www.desmos.com/calculator", labels: ["Maths", "Graphing"], status: "Rough" },
  { id: "desmos-sci", name: "Desmos Scientific", kind: "app", file: "https://www.desmos.com/scientific", labels: ["Maths", "Calculator"], status: "Rough" },
  { id: "carbon", name: "Carbon", kind: "app", file: "https://carbon.now.sh/", labels: ["Code", "Screenshots"], status: "Fine" },
  { id: "codepen", name: "CodePen", kind: "app", file: "https://codepen.io/pen/", labels: ["Code", "Playground"], status: "Rough" },
  { id: "jsfiddle", name: "JSFiddle", kind: "app", file: "https://jsfiddle.net/", labels: ["Code", "Playground"], status: "Rough" },
  { id: "jsoncrack", name: "JSON Crack", kind: "app", file: "https://jsoncrack.com/editor", labels: ["Code", "Data"], status: "Fine" },
  { id: "regex101", name: "Regex101", kind: "app", file: "https://regex101.com/", labels: ["Code", "Text"], status: "Rough" },
  { id: "dillinger", name: "Dillinger", kind: "app", file: "https://dillinger.io/", labels: ["Writing", "Markdown"], status: "Fine" },
  { id: "stackedit", name: "StackEdit", kind: "app", file: "https://stackedit.io/app", labels: ["Writing", "Markdown"], status: "Rough" },
  { id: "notepad", name: "Notepad", kind: "app", file: "https://notepad.js.org/", labels: ["Writing", "Notes"], status: "Fine" },
  { id: "coolors", name: "Coolors", kind: "app", file: "https://coolors.co/", labels: ["Design", "Colour"], status: "Rough" },
  { id: "contrast", name: "Contrast Checker", kind: "app", file: "https://colourcontrast.cc/", labels: ["Design", "Colour"], status: "Fine" },
  { id: "type-scale", name: "Type Scale", kind: "app", file: "https://typescale.com/", labels: ["Design", "Type"], status: "Fine" },
  { id: "monkeytype", name: "Monkeytype", kind: "app", file: "https://monkeytype.com/", labels: ["Typing", "Games"], status: "Fine" },
  { id: "radio-garden", name: "Radio Garden", kind: "app", file: "https://radio.garden/", labels: ["Music", "Maps"], status: "Rough" },
  { id: "photopea-vect", name: "Vector Paint", kind: "app", file: "https://vectorpaint.yaks.co.nz/", labels: ["Drawing", "SVG"], status: "Fine" },
  { id: "tables", name: "Table Generator", kind: "app", file: "https://www.tablesgenerator.com/", labels: ["Writing", "Tools"], status: "Rough" },
  { id: "seq", name: "Sequence Diagrams", kind: "app", file: "https://sequencediagram.org/", labels: ["Drawing", "Code"], status: "Fine" },
  { id: "bpmn", name: "Flowcharts", kind: "app", file: "https://app.diagrams.net/", labels: ["Drawing", "Boards"], status: "Rough" },
  { id: "tex", name: "TeX Paste", kind: "app", file: "https://texpaste.com/", labels: ["Maths", "Code"], status: "Fine" },
  { id: "omnicalc", name: "Omni Calculator", kind: "app", file: "https://www.omnicalculator.com/", labels: ["Maths", "Calculator"], status: "Rough" },
];

const PROXIES: Entry[] = [
  {
    id: "internet-archive",
    name: "Internet Archive",
    kind: "proxy",
    url: "https://archive.org/",
    labels: ["Archive", "Books", "Software"],
    status: "Fine",
  },
  {
    id: "wikipedia",
    name: "Wikipedia",
    kind: "proxy",
    url: "https://www.wikipedia.org/",
    labels: ["Reference", "Reading"],
    status: "Fine",
  },
  {
    id: "openstreetmap",
    name: "Openstreetmap",
    kind: "proxy",
    url: "https://www.openstreetmap.org/",
    labels: ["Maps", "Reference"],
    status: "Rough",
  },
];

/** Where the shelves are mirrored. raw.githack and nothing else: it is the
 *  one host that hands html back as html and javascript back as javascript,
 *  and a browser will not run a page — or the scripts inside it — that it has
 *  been told is text. */
const MIRROR = "https://raw.githack.com";

/** What a shelf is called on a card. */
const SHELF_NAME: Record<string, string> = {
  "gmshelf/seraph": "Seraph",
  "gmshelf/truffled": "Truffled",
  "gmshelf/ckv": "CKV",
  "gmshelf/ugs": "UGS",
};

/** The address of a file inside a shelf. */
const inShelf = (shelf: string, file: string) => `${MIRROR}/${shelf}/main/${file}`;

/** The same picture at every host that serves it, best first.
 *
 *  jsDelivr leads because it is a real CDN — fast, and the most likely of the
 *  three to be allowed through a school filter. It is left out for ckv, which
 *  is over jsDelivr's package limit: over there every file in the repo, images
 *  included, answers 403. Then GitHub's own file host, then the mirror the
 *  games themselves are served through. */
function coverHosts(shelf: string, cover: string): string[] {
  const out = [
    `https://raw.githubusercontent.com/${shelf}/main/${cover}`,
    inShelf(shelf, cover),
  ];
  if (shelf !== "gmshelf/ckv") out.unshift(`https://cdn.jsdelivr.net/gh/${shelf}@main/${cover}`);
  return out;
}

/** Discovered games, marked as remote so a card can say where it loads from.
 *  Local entries win a name clash: this repo's own shelf is always the one
 *  it serves. */
function discovered(): Entry[] {
  const local = new Set(GAMES.map((g) => g.name.toLowerCase()));
  return ROWS.filter(([, name]) => !local.has(name.toLowerCase())).map(
    ([id, name, shelf, file, coverShelf, cover, genre]) => {
      const art = cover ? coverHosts(coverShelf, cover) : [];
      return {
        id,
        name,
        kind: "game" as const,
        file: inShelf(shelf, file),
        ...(art.length ? { thumb: art[0], thumbs: art } : {}),
        labels: [SHELF_NAME[shelf] ?? shelf, ...(genre ? [genre] : []), "Remote"],
        status: "Remote" as const,
      };
    },
  );
}

/** Everything this repo serves or mirrors, before the cloud titles. */
const SHELF: Entry[] = [...GAMES, ...discovered()];

/** The cloud catalogue, which is browsable and not playable here. Anything the
 *  shelf already carries is left to the shelf: a game with a file is a game you
 *  can play, and a card for one should not be a card you cannot. */
function cloudGames(): Entry[] {
  const known = new Set(SHELF.map((e) => e.name.toLowerCase()));
  return CLOUD.filter(([, name]) => !known.has(name.toLowerCase())).map(
    ([id, name, key, cover, tags]) => ({
      id,
      name,
      kind: "game" as const,
      url: CLOUD_SITE,
      ...(cover ? { thumb: cover } : {}),
      labels: ["Cloud", ...tags, "Remote"],
      status: "Remote" as const,
      /* the key is what the service files it under, which is the one useful
         thing to print on a card that cannot be launched */
      warning: {
        title: `${name} (${key}) runs in the cloud`,
        body: "Cloud titles are streamed by a service that holds the licence, so NULL cannot copy one into a frame to play. Opening the service is where it plays.",
      },
    }),
  );
}

export const LIBRARY: Record<Kind, Entry[]> = {
  game: [...SHELF, ...cloudGames()],
  app: APPS,
  proxy: PROXIES,
};

export function entries(kind: Kind): Entry[] {
  return LIBRARY[kind];
}

export function find(kind: Kind, id: string): Entry | undefined {
  return LIBRARY[kind].find((e) => e.id === id);
}

/** Where each entry came from, for the source dropdown: a discovered game
 *  carries the stash it was pulled from as its first label, and anything this
 *  repo serves itself answers to NULL. "Remote" is not a source, it is a note
 *  about how the card loads, so it is left out. */
const NOT_A_SOURCE = new Set(["Remote"]);

export function sources(kind: Kind): { id: string; count: number }[] {
  const tally = new Map<string, number>();
  LIBRARY[kind].forEach((e) => {
    const from = e.labels.find((l) => !NOT_A_SOURCE.has(l)) ?? "NULL";
    tally.set(from, (tally.get(from) ?? 0) + 1);
  });
  return [...tally.entries()]
    .map(([id, count]) => ({ id, count }))
    .sort((a, b) => b.count - a.count || a.id.localeCompare(b.id));
}

/** Every category in one kind, alphabetical, for the filters row. */
export function categories(kind: Kind): string[] {
  const seen = new Set<string>();
  LIBRARY[kind].forEach((e) => e.labels.forEach((l) => seen.add(l)));
  return [...seen].sort((a, b) => a.localeCompare(b));
}

export function counts() {
  return {
    game: LIBRARY.game.length,
    app: LIBRARY.app.length,
    proxy: LIBRARY.proxy.length,
  };
}

export type SortId = "az" | "za" | "new" | "random";

export const SORTS: { id: SortId; name: string }[] = [
  { id: "az", name: "A to Z" },
  { id: "za", name: "Z to A" },
  { id: "new", name: "Recently added" },
  { id: "random", name: "Shuffled" },
];

/** Filter + sort in one pass.
 *
 *  The search is fuzzy and forgiving: every word typed has to be found
 *  somewhere in the name or the labels — "srprow" still finds "Superhot" —
 *  by the oldest trick in the book, the subsequence match, backed up by a
 *  plain substring hit and a three-letter prefix hit. What it does not do
 *  is rank one entry above another on a hunch: an exact hit and a scattershot
 *  one both simply stay on the shelf. */
export function browse(
  kind: Kind,
  opts: { q?: string; sort?: SortId; onlyIds?: string[]; seed?: number; source?: string },
): Entry[] {
  const q = (opts.q ?? "").trim().toLowerCase();
  const sort = opts.sort ?? "az";
  let list = LIBRARY[kind].slice();

  if (opts.onlyIds) {
    const set = new Set(opts.onlyIds);
    list = list.filter((e) => set.has(e.id));
  }
  if (opts.source) {
    list = list.filter((e) => (e.labels.find((l) => !NOT_A_SOURCE.has(l)) ?? "NULL") === opts.source);
  }
  if (q) {
    const words = q.split(/\s+/).filter(Boolean);
    list = list.filter((e) => {
      const hay = `${e.name} ${e.id} ${e.labels.join(" ")}`.toLowerCase();
      return words.every((w) => hay.includes(w) || wobbly(hay, w) || prefixish(hay, w));
    });
  }

  if (sort === "az") list.sort((a, b) => a.name.localeCompare(b.name));
  else if (sort === "za") list.sort((a, b) => b.name.localeCompare(a.name));
  else if (sort === "random") list = shuffled(list, opts.seed ?? 7);

  return list;
}

/** A subsequence match with the fuzz left in: every letter of `needle` in
 *  order inside `hay`, and up to two of them allowed to be missing entirely,
 *  so a mistyped middle still lands. "srprow" finds "superhot"; "xyzzy"
 *  finds nothing. */
function wobbly(hay: string, needle: string): boolean {
  let at = 0;
  let skipped = 0;
  for (const ch of needle) {
    const hit = hay.indexOf(ch, at);
    if (hit < 0) {
      skipped += 1;
      if (skipped > 2) return false;
      continue;
    }
    at = hit + 1;
  }
  return true;
}

/** A three-letter-or-longer word also matches a word it starts: "mario"
 *  finds "Mario Kart" without any fuzzy work at all. */
function prefixish(hay: string, needle: string): boolean {
  return needle.length >= 3 && hay.split(/\s+/).some((w) => w.startsWith(needle));
}

function shuffled<T>(list: T[], seed: number): T[] {
  const out = list.slice();
  let s = seed || 1;
  for (let i = out.length - 1; i > 0; i--) {
    s = (s * 1103515245 + 12345) & 0x7fffffff;
    const j = s % (i + 1);
    [out[i], out[j]] = [out[j], out[i]];
  }
  return out;
}
