/* NULL · catalog.ts
   The library. Entries are plain objects: adding a game is adding a line.

   Two shelves feed it. The hand-written ones below are files this repo
   serves itself. On top of them sits `discovered.ts`, generated by
   scripts/discover-games.mjs from the gmshelf shelves (seraph, truffled, the
   Chicken King's Vault and the Ultimate Game Stash) — thousands of games
   nobody had to type in. Nothing is fetched at runtime: the shelf is a file in
   the repo, rebuilt whenever the script runs.

   A discovered row is a path, not an address, which is what keeps two and a
   half thousand of them to a couple of hundred kilobytes. The shelves are all
   mirrored by raw.githack, and that expansion happens here, once.

   `file` is either a real path inside the built site or an https URL; the
   player frames the first kind directly and bridges the second (see
   Player.tsx). `thumb` is optional artwork, same deal. */

/* ---------- the cloud catalogue ----------
   Where cloud titles are played from. The shelf's list of keys comes from
   stratus-api, and the service that actually streams a session is separate —
   anybody can run one (see that repo's api folder), so the player page inside
   the service is what a cloud entry opens. NULL frames that page the way it
   frames a game, and the stream plays in place.

   The default service is the one the shelf's authors run. If it is quiet,
   Settings → Browser takes the address of another.

   A cloud row carries BOTH fields, on purpose: `file` is the framed stream,
   and `url` is the same service in a real tab, for when a stream refuses a
   frame and the player's route button needs somewhere honest to send it. */
import { CLOUD, ROWS } from "./discovered";
import { prefs } from "./themes";

export type Kind = "game" | "app" | "proxy";

export const CLOUD_SITE = "https://cherrion.top/";

/** The service in use right now: the setting when there is one, the default
 *  when there is not. Read through a function rather than at import time so
 *  a change in Settings takes effect on the next card that opens. */
export function cloudSite(): string {
  const broker = prefs.get().cloudBroker.trim();
  return broker || CLOUD_SITE;
}

/** The address a cloud title is played at: the service's own player page,
 *  keyed by the service's key for that title. */
export function cloudPlayUrl(key: string): string {
  const base = cloudSite().replace(/\/+$/, "");
  return `${base}/play?game=${encodeURIComponent(key)}`;
}

export type Entry = {
  id: string;
  name: string;
  kind: Kind;
  /** where it opens. A game or app: a file or URL. A proxy: a site. */
  file?: string;
  url?: string;
  /** optional artwork. Without one the card shows a drawn square instead */
  thumb?: string;
  /** the same artwork at other addresses, best first. `thumb` is the first of
   *  them: a filtered network refuses whole hosts, and one refused host should
   *  not cost a card its picture (see Cover.tsx) */
  thumbs?: string[];
  labels: string[];
  status?: "Fine" | "Rough" | "Blocked" | "Remote";
  warning?: { title: string; body: string };
};

const GAMES: Entry[] = [];

/* ---------- apps ----------
   The apps shelf is the web's own front doors: the sites people are actually
   going to open on a school machine. Every one of these is somebody else's
   site, opened the way the games are — through the player, which tries a
   copy, then an inline mount, then a plain frame — so the shelf is a list of
   places, not a list of widgets.

   `status` is about the frame and nothing else: "Fine" is a page that
   happily lives inside one (most of the static ones, and anything on GitHub
   Pages), "Rough" is a site that may refuse to be framed and is best opened
   through the proxy window instead. The player's route button walks a Rough
   one on to the next road, which is usually enough. */
const APPS: Entry[] = [
  { id: "youtube", name: "YouTube", kind: "app", file: "https://www.youtube.com/", labels: ["Video", "Media"], status: "Rough" },
  { id: "github", name: "GitHub", kind: "app", file: "https://github.com/", labels: ["Code", "Dev"], status: "Rough" },
  { id: "spotify", name: "Spotify", kind: "app", file: "https://open.spotify.com/", labels: ["Music", "Media"], status: "Rough" },
  { id: "discord", name: "Discord", kind: "app", file: "https://discord.com/app", labels: ["Chat", "Social"], status: "Rough" },
  { id: "reddit", name: "Reddit", kind: "app", file: "https://old.reddit.com/", labels: ["Social", "Reading"], status: "Rough" },
  { id: "x", name: "X", kind: "app", file: "https://x.com/", labels: ["Social", "Media"], status: "Rough" },
  { id: "instagram", name: "Instagram", kind: "app", file: "https://www.instagram.com/", labels: ["Social", "Images"], status: "Rough" },
  { id: "tiktok", name: "TikTok", kind: "app", file: "https://www.tiktok.com/", labels: ["Video", "Social"], status: "Rough" },
  { id: "twitch", name: "Twitch", kind: "app", file: "https://www.twitch.tv/", labels: ["Video", "Streaming"], status: "Rough" },
  { id: "netflix", name: "Netflix", kind: "app", file: "https://www.netflix.com/", labels: ["Movies", "Media"], status: "Rough" },
  { id: "primevideo", name: "Prime Video", kind: "app", file: "https://www.primevideo.com/", labels: ["Movies", "Media"], status: "Rough" },
  { id: "crunchyroll", name: "Crunchyroll", kind: "app", file: "https://www.crunchyroll.com/", labels: ["Anime", "Media"], status: "Rough" },
  { id: "roblox", name: "Roblox", kind: "app", file: "https://www.roblox.com/", labels: ["Games", "Platform"], status: "Rough" },
  { id: "steam", name: "Steam", kind: "app", file: "https://store.steampowered.com/", labels: ["Games", "Store"], status: "Rough" },
  { id: "epic", name: "Epic Games", kind: "app", file: "https://store.epicgames.com/", labels: ["Games", "Store"], status: "Rough" },
  { id: "chess", name: "Chess.com", kind: "app", file: "https://www.chess.com/", labels: ["Games", "Chess"], status: "Rough" },
  { id: "lichess", name: "Lichess", kind: "app", file: "https://lichess.org/", labels: ["Games", "Chess"], status: "Fine" },
  { id: "coolmath", name: "Coolmath Games", kind: "app", file: "https://www.coolmathgames.com/", labels: ["Games", "Web"], status: "Rough" },
  { id: "poki", name: "Poki", kind: "app", file: "https://poki.com/", labels: ["Games", "Web"], status: "Rough" },
  { id: "itch", name: "itch.io", kind: "app", file: "https://itch.io/", labels: ["Games", "Indie"], status: "Rough" },
  { id: "crazygames", name: "CrazyGames", kind: "app", file: "https://www.crazygames.com/", labels: ["Games", "Web"], status: "Rough" },
  { id: "monkeytype", name: "Monkeytype", kind: "app", file: "https://monkeytype.com/", labels: ["Typing", "Games"], status: "Fine" },
  { id: "wikipedia", name: "Wikipedia", kind: "app", file: "https://www.wikipedia.org/", labels: ["Reference", "Reading"], status: "Fine" },
  { id: "archive", name: "Internet Archive", kind: "app", file: "https://archive.org/", labels: ["Archive", "Reference"], status: "Fine" },
  { id: "gmail", name: "Gmail", kind: "app", file: "https://mail.google.com/", labels: ["Mail", "Google"], status: "Rough" },
  { id: "docs", name: "Google Docs", kind: "app", file: "https://docs.google.com/document/u/0/", labels: ["Writing", "Google"], status: "Rough" },
  { id: "classroom", name: "Google Classroom", kind: "app", file: "https://classroom.google.com/", labels: ["School", "Google"], status: "Rough" },
  { id: "drive", name: "Google Drive", kind: "app", file: "https://drive.google.com/", labels: ["Files", "Google"], status: "Rough" },
  { id: "gemini", name: "Gemini", kind: "app", file: "https://gemini.google.com/", labels: ["AI", "Google"], status: "Rough" },
  { id: "chatgpt", name: "ChatGPT", kind: "app", file: "https://chatgpt.com/", labels: ["AI", "Tools"], status: "Rough" },
  { id: "telegram", name: "Telegram", kind: "app", file: "https://web.telegram.org/a/", labels: ["Chat", "Social"], status: "Rough" },
  { id: "pinterest", name: "Pinterest", kind: "app", file: "https://www.pinterest.com/", labels: ["Images", "Social"], status: "Rough" },
  { id: "imgur", name: "Imgur", kind: "app", file: "https://imgur.com/", labels: ["Images", "Social"], status: "Rough" },
  { id: "photopea", name: "Photopea", kind: "app", file: "https://www.photopea.com/", labels: ["Images", "Editing"], status: "Fine" },
  { id: "desmos", name: "Desmos", kind: "app", file: "https://www.desmos.com/calculator", labels: ["Maths", "School"], status: "Rough" },
  { id: "cyberchef", name: "CyberChef", kind: "app", file: "https://gchq.github.io/CyberChef/", labels: ["Tools", "Dev"], status: "Fine" },
];

const PROXIES: Entry[] = [
  {
    id: "internet-archive",
    name: "Internet Archive",
    kind: "proxy",
    url: "https://archive.org/",
    labels: ["Archive", "Books", "Software"],
    status: "Fine",
  },
  {
    id: "wikipedia",
    name: "Wikipedia",
    kind: "proxy",
    url: "https://www.wikipedia.org/",
    labels: ["Reference", "Reading"],
    status: "Fine",
  },
  {
    id: "openstreetmap",
    name: "Openstreetmap",
    kind: "proxy",
    url: "https://www.openstreetmap.org/",
    labels: ["Maps", "Reference"],
    status: "Rough",
  },
];

/** Where the shelves are mirrored. raw.githack and nothing else: it is the
 *  one host that hands html back as html and javascript back as javascript,
 *  and a browser will not run a page — or the scripts inside it — that it has
 *  been told is text. */
const MIRROR = "https://raw.githack.com";

/** What a shelf is called on a card. */
const SHELF_NAME: Record<string, string> = {
  "gmshelf/seraph": "Seraph",
  "gmshelf/truffled": "Truffled",
  "gmshelf/ckv": "CKV",
  "gmshelf/ugs": "UGS",
};

/** The address of a file inside a shelf. */
const inShelf = (shelf: string, file: string) => `${MIRROR}/${shelf}/main/${file}`;

/** The same picture at every host that serves it, best first.
 *
 *  jsDelivr leads because it is a real CDN — fast, and the most likely of the
 *  three to be allowed through a school filter. It is left out for ckv, which
 *  is over jsDelivr's package limit: over there every file in the repo, images
 *  included, answers 403. Then GitHub's own file host, then the mirror the
 *  games themselves are served through. */
function coverHosts(shelf: string, cover: string): string[] {
  const out = [
    `https://raw.githubusercontent.com/${shelf}/main/${cover}`,
    inShelf(shelf, cover),
  ];
  if (shelf !== "gmshelf/ckv") out.unshift(`https://cdn.jsdelivr.net/gh/${shelf}@main/${cover}`);
  return out;
}

/** Discovered games, marked as remote so a card can say where it loads from.
 *  Local entries win a name clash: this repo's own shelf is always the one
 *  it serves. */
function discovered(): Entry[] {
  const local = new Set(GAMES.map((g) => g.name.toLowerCase()));
  return ROWS.filter(([, name]) => !local.has(name.toLowerCase())).map(
    ([id, name, shelf, file, coverShelf, cover, genre]) => {
      const art = cover ? coverHosts(coverShelf, cover) : [];
      return {
        id,
        name,
        kind: "game" as const,
        file: inShelf(shelf, file),
        ...(art.length ? { thumb: art[0], thumbs: art } : {}),
        labels: [SHELF_NAME[shelf] ?? shelf, ...(genre ? [genre] : []), "Remote"],
        status: "Remote" as const,
      };
    },
  );
}

/** Everything this repo serves or mirrors, before the cloud titles. */
const SHELF: Entry[] = [...GAMES, ...discovered()];

/** The cloud catalogue. Anything the shelf already carries is left to the
 *  shelf: a game with a real file is a game you can play, and a card for one
 *  should not be a card that streams instead. The rest play in NULL through
 *  the service's player page, framed like any other game. */
function cloudGames(): Entry[] {
  const known = new Set(SHELF.map((e) => e.name.toLowerCase()));
  return CLOUD.filter(([, name]) => !known.has(name.toLowerCase())).map(
    ([id, name, key, cover, tags]) => ({
      id,
      name,
      kind: "game" as const,
      file: cloudPlayUrl(key),
      url: cloudSite(),
      ...(cover ? { thumb: cover } : {}),
      labels: ["Cloud", ...tags, "Remote"],
      status: "Remote" as const,
      /* the key is what the service files it under — worth printing, because
         it is the handle another service would know the title by */
      warning: {
        title: `${name} (${key}) streams from the cloud`,
        body: "This one is played on a cloud gaming service, and NULL opens its stream right here. Sessions are served in turns, so at busy times there is a short queue.",
      },
    }),
  );
}

export const LIBRARY: Record<Kind, Entry[]> = {
  game: [...SHELF, ...cloudGames()],
  app: APPS,
  proxy: PROXIES,
};

export function entries(kind: Kind): Entry[] {
  return LIBRARY[kind];
}

export function find(kind: Kind, id: string): Entry | undefined {
  return LIBRARY[kind].find((e) => e.id === id);
}

/** Where each entry came from, for the source dropdown: a discovered game
 *  carries the stash it was pulled from as its first label, and anything this
 *  repo serves itself answers to NULL. "Remote" is not a source, it is a note
 *  about how the card loads, so it is left out. */
const NOT_A_SOURCE = new Set(["Remote"]);

export function sources(kind: Kind): { id: string; count: number }[] {
  const tally = new Map<string, number>();
  LIBRARY[kind].forEach((e) => {
    const from = e.labels.find((l) => !NOT_A_SOURCE.has(l)) ?? "NULL";
    tally.set(from, (tally.get(from) ?? 0) + 1);
  });
  return [...tally.entries()]
    .map(([id, count]) => ({ id, count }))
    .sort((a, b) => b.count - a.count || a.id.localeCompare(b.id));
}

/** Every category in one kind, alphabetical, for the filters row. */
export function categories(kind: Kind): string[] {
  const seen = new Set<string>();
  LIBRARY[kind].forEach((e) => e.labels.forEach((l) => seen.add(l)));
  return [...seen].sort((a, b) => a.localeCompare(b));
}

export function counts() {
  return {
    game: LIBRARY.game.length,
    app: LIBRARY.app.length,
    proxy: LIBRARY.proxy.length,
  };
}

export type SortId = "az" | "za" | "new" | "random";

export const SORTS: { id: SortId; name: string }[] = [
  { id: "az", name: "A to Z" },
  { id: "za", name: "Z to A" },
  { id: "new", name: "Recently added" },
  { id: "random", name: "Shuffled" },
];

/** Filter + sort in one pass.
 *
 *  The search is fuzzy and forgiving: every word typed has to be found
 *  somewhere in the name or the labels — "srprow" still finds "Superhot" —
 *  by the oldest trick in the book, the subsequence match, backed up by a
 *  plain substring hit and a three-letter prefix hit. What it does not do
 *  is rank one entry above another on a hunch: an exact hit and a scattershot
 *  one both simply stay on the shelf. */
export function browse(
  kind: Kind,
  opts: { q?: string; sort?: SortId; onlyIds?: string[]; seed?: number; source?: string },
): Entry[] {
  const q = (opts.q ?? "").trim().toLowerCase();
  const sort = opts.sort ?? "az";
  let list = LIBRARY[kind].slice();

  if (opts.onlyIds) {
    const set = new Set(opts.onlyIds);
    list = list.filter((e) => set.has(e.id));
  }
  if (opts.source) {
    list = list.filter((e) => (e.labels.find((l) => !NOT_A_SOURCE.has(l)) ?? "NULL") === opts.source);
  }
  if (q) {
    const words = q.split(/\s+/).filter(Boolean);
    list = list.filter((e) => {
      const hay = `${e.name} ${e.id} ${e.labels.join(" ")}`.toLowerCase();
      return words.every((w) => hay.includes(w) || wobbly(hay, w) || prefixish(hay, w));
    });
  }

  if (sort === "az") list.sort((a, b) => a.name.localeCompare(b.name));
  else if (sort === "za") list.sort((a, b) => b.name.localeCompare(a.name));
  else if (sort === "random") list = shuffled(list, opts.seed ?? 7);

  return list;
}

/** A subsequence match with the fuzz left in: every letter of `needle` in
 *  order inside `hay`, and up to two of them allowed to be missing entirely,
 *  so a mistyped middle still lands. "srprow" finds "superhot"; "xyzzy"
 *  finds nothing. */
function wobbly(hay: string, needle: string): boolean {
  let at = 0;
  let skipped = 0;
  for (const ch of needle) {
    const hit = hay.indexOf(ch, at);
    if (hit < 0) {
      skipped += 1;
      if (skipped > 2) return false;
      continue;
    }
    at = hit + 1;
  }
  return true;
}

/** A three-letter-or-longer word also matches a word it starts: "mario"
 *  finds "Mario Kart" without any fuzzy work at all. */
function prefixish(hay: string, needle: string): boolean {
  return needle.length >= 3 && hay.split(/\s+/).some((w) => w.startsWith(needle));
}

function shuffled<T>(list: T[], seed: number): T[] {
  const out = list.slice();
  let s = seed || 1;
  for (let i = out.length - 1; i > 0; i--) {
    s = (s * 1103515245 + 12345) & 0x7fffffff;
    const j = s % (i + 1);
    [out[i], out[j]] = [out[j], out[i]];
  }
  return out;
}
