/* ============================================================
   NULL — generated-catalog.js
   AUTO-GENERATED by scripts/build-catalog.js — do not edit by hand.
   Rebuild with: bun run catalog
   ============================================================ */
window.NULL_CATALOG = {
  "site": "NULL",
  "generatedAt": "2026-09-03T18:37:28.757Z",
  "games": [
    {
      "id": "flip",
      "name": "Flip",
      "desc": "Found automatically in games/flip — part of the NULL library.",
      "file": "/games/flip/flip.html",
      "thumb": "/games/flip/flip.svg",
      "labels": [
        "Puzzle",
        "Memory",
        "Singleplayer",
        "Card",
        "Game"
      ],
      "warning": null
    },
    {
      "id": "pulse",
      "name": "Pulse",
      "desc": "Found automatically in games/pulse — part of the NULL library.",
      "file": "/games/pulse/pulse.html",
      "thumb": "/games/pulse/pulse.svg",
      "labels": [
        "Action",
        "Arcade",
        "2",
        "Player",
        "Local",
        "Multiplayer",
        "Pong"
      ],
      "warning": {
        "title": "Heads up — PULSE",
        "description": "PULSE uses the keyboard (W/S or arrows) and has sound-free retro vibes. First to 7 wins.\nSpace serves the ball. Touch devices can drag on the left/right half of the screen."
      }
    },
    {
      "id": "trace",
      "name": "Trace",
      "desc": "Found automatically in games/trace — part of the NULL library.",
      "file": "/games/trace/trace.html",
      "thumb": "/games/trace/trace.svg",
      "labels": [
        "Arcade",
        "Puzzle",
        "Singleplayer",
        "Retro"
      ],
      "warning": null
    }
  ],
  "apps": [
    {
      "id": "pad",
      "name": "Pad",
      "desc": "Found automatically in apps/pad — part of the NULL library.",
      "file": "/apps/pad/pad.html",
      "thumb": "/apps/pad/pad.svg",
      "labels": [
        "Creative",
        "Tool",
        "Whiteboard",
        "Drawing",
        "Offline"
      ],
      "warning": null
    },
    {
      "id": "stopwatch",
      "name": "Stopwatch",
      "desc": "Found automatically in apps/stopwatch — part of the NULL library.",
      "file": "/apps/stopwatch/stopwatch.html",
      "thumb": "/apps/stopwatch/stopwatch.svg",
      "labels": [
        "Utility",
        "Timer",
        "Tools",
        "Offline"
      ],
      "warning": null
    }
  ],
  "proxies": [
    {
      "id": "internet-archive",
      "name": "Internet Archive",
      "url": "https://archive.org/",
      "desc": "Millions of books, software, audio and old web pages.",
      "status": "All Good"
    },
    {
      "id": "openstreetmap",
      "name": "Openstreetmap",
      "url": "https://www.openstreetmap.org/",
      "desc": "The free, editable world map. May be blocked on some networks.",
      "status": "Issue"
    },
    {
      "id": "wikipedia",
      "name": "Wikipedia",
      "url": "https://www.wikipedia.org/",
      "desc": "The free encyclopedia — quick research and reading.",
      "status": "All Good"
    }
  ]
};
