/* NULL — build-catalog.js
   Generates src/catalog/generated-catalog.js from the games/, apps/ and
   proxies/ folders. Generated output — run "bun run catalog" (or
   "node scripts/build-catalog.js") after adding content. */
import fs from "node:fs";
import path from "node:path";
import { discoverContent } from "./discover-content.js";

const ROOT = process.cwd();
const OUT = path.join(ROOT, "src", "catalog", "generated-catalog.js");

const catalog = discoverContent(ROOT);

const body =
  "/* ============================================================\n" +
  "   NULL — generated-catalog.js\n" +
  "   AUTO-GENERATED by scripts/build-catalog.js — do not edit by hand.\n" +
  "   Rebuild with: bun run catalog\n" +
  "   ============================================================ */\n" +
  "window.NULL_CATALOG = " +
  JSON.stringify(
    {
      site: catalog.site,
      generatedAt: catalog.generatedAt,
      games: catalog.games,
      apps: catalog.apps,
      proxies: catalog.proxies,
    },
    null,
    2,
  ) +
  ";\n";

fs.mkdirSync(path.dirname(OUT), { recursive: true });
fs.writeFileSync(OUT, body);

console.log("catalog written: " + path.relative(ROOT, OUT));
console.log(
  "  games   " +
    catalog.games.length +
    (catalog.notes.skippedGames.length ? "  (skipped: " + catalog.notes.skippedGames.join(", ") + ")" : ""),
);
console.log(
  "  apps    " +
    catalog.apps.length +
    (catalog.notes.skippedApps.length ? "  (skipped: " + catalog.notes.skippedApps.join(", ") + ")" : ""),
);
console.log(
  "  proxies " +
    catalog.proxies.length +
    (catalog.notes.skippedProxies.length ? "  (skipped: " + catalog.notes.skippedProxies.join(", ") + ")" : ""),
);
