import { JSDOM, VirtualConsole } from "jsdom";
const vc = new VirtualConsole();
vc.on("jsdomError", () => {});
const dom = await JSDOM.fromFile("settings.html", { runScripts: "dangerously", resources: "usable", pretendToBeVisual: true, virtualConsole: vc });
await new Promise((r) => dom.window.addEventListener("load", r));
await new Promise((r) => setTimeout(r, 400));
const w = dom.window, d = w.document;
const root = d.documentElement;
console.log("on load  data-nav:", JSON.stringify(root.dataset.nav), "pref:", w.N.prefs.get("navLayout"));
console.log("flag navDefaultBar:", w.N.flags.get("navDefaultBar"));
const btns = d.querySelectorAll("#navSeg button");
console.log("buttons:", [...btns].map(b => b.dataset.val + (b.classList.contains("on") ? "*" : "")).join(", "));
btns[1].dispatchEvent(new w.MouseEvent("click", { bubbles: true }));
await new Promise((r) => setTimeout(r, 60));
console.log("after side click  data-nav:", JSON.stringify(root.dataset.nav), "pref:", w.N.prefs.get("navLayout"));
btns[0].dispatchEvent(new w.MouseEvent("click", { bubbles: true }));
await new Promise((r) => setTimeout(r, 60));
console.log("after bar click   data-nav:", JSON.stringify(root.dataset.nav), "pref:", w.N.prefs.get("navLayout"));
console.log("stored prefs:", w.localStorage.getItem("null:prefs"));
process.exit(0);
